### ISSUE TITLE
Buffer encrypts when file is saved

### ISSUE THREAD

**Issue by danrharms** [Sauermann/emacs-aes#4]
Kudos on the package, I use it all the time.

I was wondering if one behavior could be changed.  When I open an encrypted file, alter its contents, then save the buffer to file again, the buffer automatically encrypts.  I would rather the buffer remain decrypted so that I can continue looking at it.  Do you know the best way I could achieve that?

Thank you.

**Comment by Sauermann** [comment]
Please have a look at the commit in the develop branch. This should take care of your problem.
However I am not yet 100% content with my solution - but I will look into that soon(tm).

**Comment by danrharms** [comment]
So far so good. Initial tests look good. I will keep using it. 

Thank you very much,

Dan

**Comment by danrharms** [comment]
Hi, any plans to merge this branch to master?
Thanks again for the fix.

**Comment by Sauermann** [comment]
Thanks for the reminder. Done.
